version: "3.9"
services:
  apiapp:
    container_name: apiapp_container
    build:
      context: .
    environment:
      POSTGTRES_SQL_URI: "postgresql://mp3user:mp31234@postgres_container:5432/mp3db"
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "8080:8080"
    profiles:
      - apiapp
    stop_signal: SIGINT
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - backend

  postgres:
    container_name: postgres_container
    image: postgres:13.11
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "mp3db"
      POSTGRES_USER: "mp3user"
      POSTGRES_PASSWORD: "mp31234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - only_db
      - admin_db
      - apiapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizuser -d quizdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - backend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.1
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "mp3@quiz.com"
      PGADMIN_DEFAULT_PASSWORD: "mp31234"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - admin_db
      - apiapp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - backend

networks:
  backend:
    driver: bridge
